%% Plotting the vessels or chemical field 
%% The input data must be formatted as matrix N x L 
%% This script runs in Matlab R2017b
%% Select: p = 1 (vessels), 2 (chemical field)
p = 1;
filename = 'A.3.60000';
output_file = 'A60';
%%%%
%% code generated by Matlab import
delimiter = '\t';   %% 300 x 300 mesh - in order to change the size you need to generate a new formatSpec with N %f, where N is the number of columns of your data
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);
fclose(fileID);
A = [dataArray{1:end-1}];
clearvars filename delimiter formatSpec fileID dataArray ans;
%% end of the code generated by Matlab import
%%%%
if p==1
    colormap('Jet');
else
    colormap('Winter'); 
end

im = pcolor(A);
ax = gca;
ax.Visible = 'off';
shading interp;

print(output_file, '-dpng');
